services:
  taskmanager-backend:
    environment:
      - SPRING_PROFILES_ACTIVE=aws
      - SPA_HOST=${SPA_HOST:-http://localhost:3000}
  taskmanager-frontend:
    environment:
      - REACT_APP_API_BASE=${REACT_APP_API_BASE:-http://localhost:8080}
